apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: amqp-ingress
spec:
  entryPoints:
    - amqp1
  routes:
  - match: HostSNI(`*`)
    services:
    - name: one
      port: 5672
      terminationDelay: 400
      proxyProtocol:
        version: 1
