apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- ingress.yaml
patchesStrategicMerge:
- replicas-count.yaml
patches:
- path: common-deployment-patch.yaml
  target:
    kind: Deployment