apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
spec:
  dnsNames:
    - bun-cert-manager-demo.bun-cert-manager-demo
  secretName: tls-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer