apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bun-cert-manager-demo
  name: bun-cert-manager-demo
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bun-cert-manager-demo
  template:
    metadata:
      labels:
        app: bun-cert-manager-demo
    spec:
      containers:
      - image: ghcr.io/kszpakowski/bun-cert-manager-demo:master
        name: bun-cert-manager-demo
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 9443
        volumeMounts:
        - name: tls
          mountPath: /usr/src/app/tls
          readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: tls-cert
