apiVersion: v1
kind: Pod
metadata:
  name: crm
  labels:
    app: crm
    namespace: {{ default (ge .Capabilities.KubeVersion.Minor "20" | ternary .Release.Namespace "openshift-monitoring-apps" ) .Values.metrics.monitoringNamespace }}
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crm
  labels:
    app: crm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: crm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - crm.homelab.kszpakowski.com
      secretName: crm-cert
  rules:
  - host: "crm.homelab.kszpakowski.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crm
            port:
              number: 80
