apiVersion: v1
kind: Service
metadata:
  name: bun-cert-manager-demo
  labels:
    app: bun-cert-manager-demo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 443
      targetPort: 9443
  selector:
    app: bun-cert-manager-demo