apiVersion: v1
kind: Pod
metadata:
  name: crm
  labels:
    app: crm
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crm
  labels:
    app: crm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: crm
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crm-tls
spec:
  dnsNames:
    - crm.homelab.kszpakowski.com
  secretName: crm-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: crm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`crm.homelab.kszpakowski.com`)
      kind: Rule
      services:
        - name: crm
          port: 80
  tls:
    secretName: crm-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm
spec:
  rules:
  - host: "crm2.homelab.kszpakowski.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crm
            port:
              number: 80