apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    API_KEY: AgBz4+wt8B1TFJV6Jdk2DItCTWwSrzEW3ZFaziMR3HXlBPbGkj94tttBwWILSvU8enp0oaGC4RQLp4QoADqD8h+22CIk+Pmk6lQEvdYjpdN6rD0WE8cpAOcaheD8QBycK3NEl1mUdxdNPaKC0Ul4B9oPGZN/RHoYBmOzaSugIqaNxBIepbE4A60IMur5mZSrrsh7jBdOrMy8bML4kM2x64HvUzvKvuTpDoVf5Ms3VHWyvCHsy81zvdtW9v8MMM8mWzQGQUCDcfQFDPEgeH2JdAmuRgS/MdMWD85utgs8auHs/v0onAVWeZLsAfA4fyR2GR3bBQ4N7eI5ZHPof4vQUKJJssN9wb6xAXBH8+8rvBFFhXjJF6xTPMQ1VfdNA75KJfEo6kTTgWSSEiyVAkSBrN2CeI1LZZhJ2OnS9Nepkp6s+K2L7gUQvbpONhpCQ4vaQB5sF2RXgM9rQfxi+/JGf0bgpQx1BLhXegmWzo5ieeHu1m1CBn8DMRyIa7yA8P6sOy4saWG9Qe/svtAvcjO0IRMvVUWOFygkRcDcSdMES6JP6qR5Gps7fJF1ryVsXJd97H1IbRQXAu842CqIEueSkou8xKOa85la2dPbZ9DvBJKPbwuz7z708HI3sT80NaOhJN94WqCYaNAkkKWsm1ebJj3bGsmQJIQ6U8rFStFGZ1+VjGQY7npaa/KBO0LroraozzEq30jxiWQvS8dvJeSAYxdUaMR6I42sRtIESCd0xAAugQh6Bf/4XriL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-token
      namespace: cert-manager
