apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    API_TOKEN: AgBp/qrfevJr4u4EpTor54vPKoOywtIohjGhr/vEsyXwuRfybVbUBusFDqhbe8pBYHcsfOjzI4dr2l5tz37cHNOQr6ljHPuYTpZ848r6xrl96JhPREDQmsZ9YvLyT9Biqr9GcVsP1XHYk34CewOxUOgdZmbsgn3fZLK7uaHDYK1PvrIuytuE+fLwPxFb7uKoQEV+m1/brFBxtDybXbw+ETt7HPUZkS45RB3TpPsCQ0hrnrwHwmETY3u/41C8rZ6TD0CwkqE3G45wLTZFOxwAG5mimHyBs2TRsVP9k4k0SMr72S5Dud3ZpXrUKja2YXw6054/QxvL//Zxlxg0ebvJqRbw86sBWewveeGOMvun4losj2IPOJaqCRRPuJ2W99aL3kYZcqzWAECyXjQj9KAxfxiWUU7GuhVmVUpQMxxFpD4RLaPjcRlgBjMI3OLhOrxqqPlOvSGS6KlX6wVMS0rRJJLhAh/GRPVekJhyXv508sxsYmd0tYFNCYbYP51+j6NIAhQZ161kSgCB2DbwGg2T524tWcNXIhxeYw6A4QqMYbBM5sDdzLZZmQnEsznKX0SPx0YJAAhTbci2MRt9ySkcZZoh2CmJbCWXlCOn0NDR7JHdtqGwE5N0HTlyvNii1djw88pm2q45A93nHOYzrzzl4bFPGiO4xKVTX69KTLEEDckQqY/bKrls80g0e8pG3i1z/jRWI8cvhPBw72XVfUdHA0RioKc/QsiJwtHfHWfVdULUG5a2luSp9CD7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-token
      namespace: cert-manager
