apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    API_TOKEN: AgCsbi4sgSip10c24knUdb92Zyd8DAavtVIv3UaY3vxDNndPEd2HpNXl2wG62WIdR+ej9rL6h8KuKObKevrodDiXDKQ4DOHf8c9GJsdJWRe009qMy5VGM4GZjPA8bV4zkL4Xam1o5efU0Y4vPS6T/P37Mvoy5AsphhxR1EcfOBClGz5rx74nGpX6isi7jXLk6bigk7ZoOD0E42PeqVZq42z2z1pZ7Vi1h0WGgvwatRoVN2Z1kvg0uOb5XXKrBtz4mP0trh+U4Iae8UxGM8h4Nl3Ma4Ck93F5MfWYDoErj4O969Vy6n1DXHNTlBjGww5TrZA15WPRwsMdOod2322gaXLU+VyTA9B/PbOrdQVJm+6ZQIDMVacgQXqe8xp4I0tGofqRmcME4T7ibAGCsj8FJbcHrTVlCChekFFf18aq3ypW5pE7w1LG0sXfRyUHx4vmVF16rqb1FpyozGYZLfJknH1MBtZ+z2653ub9Wu8Yj9WrVAzuyWKXmOpu485XWThCu08CRIeUdrhZuZpygo24zxOW44qr5vNJOszcUboFk+0GkA9to/L22brzQu/OFKgkG01J69iIKNgB5+I1Gsvk40NC4eUmCRhZGEnKfADjYi/PNbHOulA7G34WEveIgsVcBvHWsd8ZwdL6N6hp6nUw72ocwqXqnLunVUNoA7jDttP6jeB4p/Kbfs9pRSyTHPhdKRQfYZoPcYw2Xb2BVnhd
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-token
      namespace: cert-manager
