apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-db-secret
  namespace: keycloak-operator
spec:
  encryptedData:
    password: AgAhLfQcuoBPipTBlR41K47m207xAYHovXRq9Q/j4tTWcdRj8lvjQr6Q/rsCPjcT0C3zjGnOUY5lWFDWcHHiZoRCVarS844pzjMvcSs5gTixDdl+31yjSDjqA/bWViSaqiasG2boy8Ai57t8GNGON/yzU+OarVkqXqkZ8I4hcCEylre3g7RY+jYbCKAHjODVBW9tg8W7dCFZ2KJYnXIoCx81YTUI43V0brOj8FtPWhaDvGCBvv9EPn5qyYh9pQRrvkmATbbblasFhsiP08jiAgGwC1CDYK43FP9ueivftCiv0Ow+b1ivdqYwCE0eeidCc5jagyoc63MGrooMgCAXU9O99uIaqty/Hq2XFPjdx0evj8/7u2QyYoQbihwyujz2mWLrkxp9Yx7w5SJJ83vdk2EJzdMPab63R7uG3KbaxQhgeuxPD+nTVwRsdAsxP6UgbrNfbWTHH8xf4IZ0tUQ76fwzusy0+V23lK+yAmyQBWyk4QDh+h4uKhGIcR7e0B3cF8RfA1XJ5ujAB42a+43iYvZbVTdP2SDMtSdAqRmhkRQLvzNAbmQxWtlBkiJusJC5W6x8E2InN/V2fYF3MpTTAlE8Ug84r/5W8PBAtwCEdfT73BKVSAbjOQpXEbQTXCXO3leToCnrA/cB2eF9pw5x4YBsoXaL0nw/0vavRzvJ7EftC9LSG/aweRFUJgo8vLKC2bYqYBXTAHyd
    username: AgCIOKivk3Wd+Kg3vmt6oWeCD7ne+Ye4TrLmQiwq6t/O8HXrjgXjWJN6vLsqD1UxYDZt3De6Rys14Kw/7Z2+B9sJpBYtWJ6D30blB6eC6WhzQL2nlOOEV7CBamcNiSfsBFWeAfVub0hhhw4PK5/cn/PjvUf/3aaXcns5SBMEe0OEXE8LSgNfhCI7/kHNZX4DSYrPkz2yuZbYwHxB5t3agKjUo2Cw9V8aTfZ4BAY8TQRQ4iltNSW9YxAcrpaWVwrGXkocRtypw3eQ99xchOnPmXnXPF0C7aGvTDJBFPRUbUFx1H8XU/BN8amxlw1G7Qcsyb4OyAUudeL7TwyYKNkJTRTnCIEc3jbg4RzOIlhoQ5+xENqWJ+u37iL3jlA2a6uwlsnoxpFFO6IYUcZO+FUccJmJOOeqO7it9eqjv2ZR2W0oNib8+s1/dkKmnHyi2JXbMy3rdmUv12hbZdqj3bbUwjdIBL5Bwly4FEClCP3kC5zUtgx+eNZsFlH0MMZ55J+KAZtHL8CSEucLMVarXGB9hQYgFL6O8fNoTu4qefq6iVOXMaKIJjHZzmK0NMUVevbvAMcRD7NSf/2UHwVioVkCMwjbjHYhl4fdA+peASHKfq+dujp2QFt5DetB7u1d91NPfsad77++pEhbpbmhHDB1KmwblD1TYPxG2D0iN0OKy2I6z8naMfjpF9Ctiosk3G9+DNNgFO8w4w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-db-secret
      namespace: keycloak-operator

