apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-crt
spec:
  secretName: keycloak-tls
  dnsNames:
  - keycloak.homelab.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io