apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
      nodePort: 30007
  selector:
    app: mosquitto
