apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: "cert-manager"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: karol.szpakowski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: API_TOKEN
    #     webhook:
    #       groupName: acme.kszpakowski.com
    #       solverName: ovh
    #       config:
    #         endpoint: ovh-eu
    #         applicationKey: 44c43c969be21335
    #         applicationSecretRef:
    #           key: applicationSecret
    #           name: ovh-credentials
    #         consumerKey: 5e28159bde0b03960354dba463839b17
