apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/configmap.yaml
- https://github.com/zalando/postgres-operator/raw/master/manifests/operator-service-account-rbac.yaml
- https://github.com/zalando/postgres-operator/raw/master/manifests/postgres-operator.yaml
- https://github.com/zalando/postgres-operator/raw/master/manifests/api-service.yaml
patches:
- path: service-account-patch.yaml
  target:
    kind: ServiceAccount
    name: postgres-operator
- path: cluster-role-binding-patch.yaml
  target:
    kind: ClusterRoleBinding
    name: postgres-operator
images:
- name: registry.opensource.zalan.do/acid/postgres-operator
  newName: ghcr.io/zalando/postgres-operator
  newTag: v1.11.0