# https://github.com/dexidp/website/blob/main/content/docs/connectors/oidc.md
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.homelab.com
  dex.config: |
    connectors:
      # - type: oidc
      #   id: keycloak
      #   name: Keycloak
      #   config:
      #     issuer: http://keycloak.keycloak/realms/kubernetes/
      #     clientID: kubernetes

      #     # Dex's issuer URL + "/callback"
      #     redirectURI: http://argocd-dex-server:5556/callback
      - type: github
        id: github
        name: GitHub
        config:
          clientID: e2ae5b8b705e0c0f16c7
          clientSecret: test
          orgs:
          - name: k13i
