# https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, ARGO_CD_ADMIN, role:admin
    g, DIGITAL_CHANNELS_DEV, role: dc_dev
    p, role:dc_dev, appliactions, get, default/nginx-demo, allow
  