# https://github.com/dexidp/website/blob/main/content/docs/connectors/oidc.md
# https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.homelab.com
  oidc.config: |
    name: Keycloak
    issuer: http://keycloak.homelab.com/realms/kubernetes
    clientID: argocd
    requestedScopes: ["openid", "profile", "email", "groups"]
