# https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  # policy.default: role:readonly
  # scopes: '[email, groups]'
  policy.csv: |
    g, ArgoCDAdmins, role:admin
  