# https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, ArgoCDAdmins, role:admin
    g, web_channels_devs, role: wc_dev
    p, role:wc_dev, appliactions, get, default/nginx-demo, allow
  