apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
spec:
  dnsNames:
    - argocd.homelab.kszpakowski.com
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer