apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: customer-platforms-connect-cluster
spec:
  version: 3.6.1
  replicas: 1
  bootstrapServers: customer-platforms-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: customer-platforms-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: customer-platforms-connect-cluster
    offset.storage.topic: customer-platforms-connect-cluster-offsets
    config.storage.topic: customer-platforms-connect-cluster-configs
    status.storage.topic: customer-platforms-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1