apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name:   POSTGRES_DB
            value:  keycloak
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: test123
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-data