apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kafka-connect
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/confluentinc/cp-helm-charts.git'
    path: 'charts/cp-kafka-connect'
    helm:
      valuesObject:
        image: ghcr.io/kszpakowski/kafka-connect-custom-image
        imageTag: main
        imagePullPolicy: Always
        kafka:
          bootstrapServers: "customer-platforms-kafka-bootstrap.kafka:9092"
        prometheus:
          jmx:
            enabled: false
        configurationOverrides:
          "plugin.path": "/opt/bitnami/kafka/libs/connectors"
          "key.converter": "org.apache.kafka.connect.json.JsonConverter"
          "value.converter": "org.apache.kafka.connect.json.JsonConverter"
          "config.storage.replication.factor": "-1"
          "offset.storage.replication.factor": "-1"
          "status.storage.replication.factor": "-1"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
