apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-worker
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rag-worker
  project: default
  source:
    directory:
      recurse: true
    path: rag-worker
    repoURL: https://github.com/kszpakowski/homelab-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true