apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-tls
  labels:
    app.kubernetes.io/component: server
spec:
  secretName: ldap-tls
  issuerRef:
    name: ca-issuer
  dnsNames:
  - homelab-directory.ldap.svc.cluster.local
  - homelab-directory.ldap
  - homelab-directory