apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-crt
spec:
  secretName: ldap-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - homelab-directory.ldap.svc.cluster.local
