apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: callback-server-cert
  namespace: "cert-manager"
spec:
  dnsNames:
  - "homebridge-daikin-callback.homebridge.cluser.local"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: callback-server-tls