apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-configmap
data:
  config.json: |
    {
        "bridge": {
            "name": "Homebridge E9B8",
            "username": "$HOMEBRIDGE_USERNAME",
            "port": 51450,
            "pin": "$HOMEBRIDGE_PIN"
        },
        "accessories": [
            {
                "name": "Termometr 1",
                "address": "58:2D:34:39:91:76",
                "temperatureName": "Temperatura",
                "humidityName": "Wilgotność",
                "fakeGatoEnabled": false,
                "timeout": 15,
                "forceDiscovering": true,
                "forceDiscoveringDelay": 2500,
                "disableBatteryLevel": false,
                "lowBattery": 10,
                "temperatureOffset": 0,
                "humidityOffset": 0,
                "accessory": "Hygrotermograph"
            },
            {
                "name": "Termometr 2",
                "address": "4C:65:A8:DF:74:D7",
                "temperatureName": "Temperatura",
                "humidityName": "Wilgotność",
                "fakeGatoEnabled": false,
                "timeout": 15,
                "forceDiscovering": true,
                "forceDiscoveringDelay": 2500,
                "disableBatteryLevel": false,
                "lowBattery": 10,
                "temperatureOffset": 0,
                "humidityOffset": 0,
                "accessory": "Hygrotermograph"
            }
        ],
        "platforms": [
            {
                "name": "Config",
                "port": 8090,
                "auth": "form",
                "theme": "auto",
                "tempUnits": "c",
                "lang": "en",
                "platform": "config"
            },
            {
                "clientId": "$DAIKIN_CLOUD_CLIENT_ID",
                "clientSecret": "$DAIKIN_CLOUD_CLIENT_SECRET",
                "callbackServerExternalAddress": "daikin-callback.homelab.kszpakowski.com/",
                "callbackServerPort": "8582",
                "oidcCallbackServerBindAddr": "0.0.0.0",
                "showExtraFeatures": false,
                "updateIntervalInMinutes": 15,
                "platform": "DaikinCloud"
            }
        ]
    }

  auth.json: |
    [
      {
          "id": 1,
          "username": "$HOMEBRIDGE_ADMIN_USER",
          "name": "$HOMEBRIDGE_ADMIN_USER",
          "hashedPassword": "$HOMEBRIDGE_ADMIN_PASSWORD",
          "salt": "$HOMEBRIDGE_ADMIN_SALT",
          "admin": true
      }
    ]
  startup.sh: |
    #!/bin/bash

    echo "install verified plugins"
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-daikin-cloud 2.2.0 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-mi-hygrothermograph 3.4.2 /var/lib/homebridge/node_modules

    echo "install envsubst"
    apt-get update
    apt-get install gettext-base

    echo "pass secrets to config files from env variables"
    envsubst < /homebridge/config.json.template > /homebridge/config.json
    envsubst < /homebridge/auth.json.template > /homebridge/auth.json
    envsubst <  /homebridge/persist/AccessoryInfo.0E83BA9DE9B8.json.template >  /homebridge/persist/AccessoryInfo.0E83BA9DE9B8.json