apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kafka-connect
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://github.com/confluentinc/cp-helm-charts.git'
    targetRevision: 'master'
    chart: cp-kafka-connect
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
