# https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kafka-connect
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/confluentinc/cp-helm-charts.git'
      path: 'charts/cp-kafka-connect'
      helm:
      valueFiles:
      - $values/values.yaml
    - repoURL: https://github.com/kszpakowski/homelab-apps.git
      path: kafka-connect
      ref: values
    
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
