apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kafka-connect
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/confluentinc/cp-helm-charts.git'
      path: 'charts/cp-kafka-connect'
      helm:
        valuesObject:
          kafka:
            image: ghcr.io/kszpakowski/kafka-connect-custom-image
            imageTag: main
            bootstrapServers: "customer-platforms-kafka-bootstrap:9092"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
