apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: localstack
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.localstack.cloud
    targetRevision: "0.6.16"
    chart: localstack
    helm:
      parameters:
        - name: mountDind.enabled
          value: "true"
        - name: debug
          value: "true"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
