apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: sealed-secrets
    repoURL: 'https://github.com/kszpakowski/homelab-apps.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true