apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rag-worker
  name: rag-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-worker
  template:
    metadata:
      labels:
        app: rag-worker
    spec:
      containers:
      - image: ghcr.io/kszpakowski/rag-worker:main
        name: rag-worker
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"