---
# Source: cert-manager-webhook-ovh/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
---
# Source: cert-manager-webhook-ovh/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh:domain-solver
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
rules:
  - apiGroups:
      - acme.kszpakowski.com
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: cert-manager-webhook-ovh/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh:flowcontrol-solver
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
rules:
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - 'prioritylevelconfigurations'
      - 'flowschemas'
    verbs:
      - 'list'
      - 'watch'
---
# Source: cert-manager-webhook-ovh/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh:auth-delegator
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kszpakowski-com-cert-manager-webhook-ovh
    namespace: cert-manager
---
# Source: cert-manager-webhook-ovh/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh:domain-solver
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kszpakowski-com-cert-manager-webhook-ovh:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: cert-manager-webhook-ovh/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh:flowcontrol-solver
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kszpakowski-com-cert-manager-webhook-ovh:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kszpakowski-com-cert-manager-webhook-ovh
    namespace: "cert-manager"
---
# Source: cert-manager-webhook-ovh/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kszpakowski-com-cert-manager-webhook-ovh
    namespace: cert-manager
---
# Source: cert-manager-webhook-ovh/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-ovh
    release: kszpakowski-com
---
# Source: cert-manager-webhook-ovh/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: cert-manager-webhook-ovh
      release: kszpakowski-com
  template:
    metadata:
      labels:
        app: cert-manager-webhook-ovh
        release: kszpakowski-com
    spec:
      serviceAccountName: kszpakowski-com-cert-manager-webhook-ovh
      containers:
        - name: cert-manager-webhook-ovh
          image: "baarde/cert-manager-webhook-ovh:0.3.1"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.kszpakowski.com"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: kszpakowski-com-cert-manager-webhook-ovh-webhook-tls
---
# Source: cert-manager-webhook-ovh/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.kszpakowski.com
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/kszpakowski-com-cert-manager-webhook-ovh-webhook-tls"
spec:
  group: acme.kszpakowski.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: kszpakowski-com-cert-manager-webhook-ovh
    namespace: cert-manager
  version: v1alpha1
---
# Source: cert-manager-webhook-ovh/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
spec:
  secretName: kszpakowski-com-cert-manager-webhook-ovh-ca
  duration: 43800h0m0s # 5y
  issuerRef:
    name: kszpakowski-com-cert-manager-webhook-ovh-selfsign
  commonName: "ca.cert-manager-webhook-ovh.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-ovh/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh-webhook-tls
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
spec:
  secretName: kszpakowski-com-cert-manager-webhook-ovh-webhook-tls
  duration: 8760h0m0s # 1y
  issuerRef:
    name: kszpakowski-com-cert-manager-webhook-ovh-ca
  dnsNames:
  - kszpakowski-com-cert-manager-webhook-ovh
  - kszpakowski-com-cert-manager-webhook-ovh.cert-manager
  - kszpakowski-com-cert-manager-webhook-ovh.cert-manager.svc
---
# Source: cert-manager-webhook-ovh/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh-selfsign
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-ovh/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kszpakowski-com-cert-manager-webhook-ovh-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh-0.3.1
    release: kszpakowski-com
    heritage: Helm
spec:
  ca:
    secretName: kszpakowski-com-cert-manager-webhook-ovh-ca
