apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homelab-kszpakowski-com
  namespace: "cert-manager"
spec:
  dnsNames:
  - "*.homelab.kszpakowski.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: wildcard-homelab-kszpakowski-com-tls