apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: karol.szpakowski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.kszpakowski.com
          solverName: ovh
          config:
            endpoint: ovh-eu
            applicationKey: 44c43c969be21335
            applicationSecretRef:
              key: applicationSecret
              name: ovh-credentials
            consumerKey: 5e28159bde0b03960354dba463839b17