apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ovh-credentials
  namespace: cert-manager
spec:
  encryptedData:
    applicationSecret: AgDgwlqjnKLBjP7nIF01fep3MsLKfflOLm82Q517D1F/CFG4IZWvklgqCZmzBVQcrxIvkGV4vd5qHqr5ytOzPnMEQE6e98sMwFVTIXveg0WwOqi39Le7DK5RBQJKEOCJpAKYdC4eO/AA7oEpNTRIlSt7yB4ydJQlFf/mwUV8zm3y+1xJFMXzIDo146I1PovTxKYkbcuj/8ziS1hw7HWk3eYffU199Iw8KFP2qDgBNjKa0CGiPDvTCcn3zs20AoqHZwZODWF1+f9xXuHDEqcQNuqdSCcsC5lpywLXzYGqVqiLmu2cDB13u3L4xfJf3szcDDE8trnM9bGcBm/v9t0M0hfxcpzAZmP/KtnSI0d6ZKubBwBnXfnmFrgj17FFYRkcZfVnxdMtgx9fPKAECxZT0vrMeyos2hsIqXqhtXYAuTYSiwvygg5hhQm6Sj9qYn9M3vVbEq4pdNDdSnpEiCSpFmrxD242qakqlpUIThZgU+TKxfUqOzLBNILW+T4uiKbedZkyEACBejWPCG00IvrDGP1qJ6NeQbXzslsJduw80UV2wU1ZzVTudkEuXXSCcZozpAVD+u15DMqVWYHv7/xIgY8hw0S6c+Yj/EfDSUz9uCimQJC5W3Qxq4SjRZbuaNoY8JOnD2O8h5UVfcC2l8kDSQ82zEC29t9CoigGZ3pq3urxvWSY2FpHwtrUYKeuiI6o8IWbCcjJxcOXjknwoP+e6a+urESDuZKeHJfeSzLoif5kNw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ovh-credentials
      namespace: cert-manager

