apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ovh-credentials
  namespace: cert-manager
spec:
  encryptedData:
    applicationSecret: AgAinkCS4mxmdRU6j8X9xDNJS/IHYj1TEbGQVOSFsK/qTNpCW5/Kyld/TLeuCsxrIscDBCAikey2mmLicWk+GEG0Gzb/gbOb58uLIfc3QC37W3oSuqbKPdjyRp81gR1/VSXXN5j+tWwbQpz5fWhNvxljI/y2fjKyqOlUorQcnRVFmm/r64CpluPhHP8xlrgP4H5bKiXp6D4ypEkrF29+0wsIT3h6S+xEqLcF4fq9/CFyvJ7ArBm9WTeMqE4Uk3QukqFr08jc9m2PK/i3vnTGBZwvdx3jJCXPfDcSd51kfbokRTqYVgPoXpckf1Kb/fYSHQJANjel6NqLRIybEYqOS4QkTBADIcpB8GG6Omp+WW1xfyCVgInnL3yT3sttQv1FjfP4BD3czNwCK/qgwowjQ5kg0xeQpA87gHpLI/tWDQMiH/b5p7H2hOZ5I7sUQVDCN5uIiYnWqHz/e55Jxw5x5Z87mHnbaO9fCs/02M1IB+EpjdIb5JUNE9E+AemfoGKM0jZyEFar0zUBf22fm3PNpa+V85wkEAVjCZ7gWU9NiLL10SgBxLAyxYMuY9W2fLMJPVxCNinnQaISyQr6lySgo+s8TybLDnYkKZ/TVCRsABuCjkTwH+PT3n5iCFlRKvCWif+Pl5kugq9aJy8e+4+vj0P+7vAwgwXkl+6xeOk9GnaPJleCf6wYS++KmXX4VR/XrjY65LQ0g9PsYm8sYFQ1kYIRhH+Tpxnr7UnNazrWxiSFXQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ovh-credentials
      namespace: cert-manager
