apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ovh-credentials
  namespace: cert-manager
spec:
  encryptedData:
    applicationSecret: AgDILC/7J1H6iPcEKmFijR6JhvXo+keM7bMCcysqUPLZ7A0KaN8HQwZteP7aEbGbiAfrhAsG2A+CK9uZKsrCUr/wnmGtvidaPoce8nIuFycyHwWQIhVt8M5jykvZxbz8K9M43YnIB4kPIoDAaplTBzjHAkfyb5iJkelqVAKYRBzNaWW9ym2DNSXIY5RfCldsajsEFfefoIDeieadGelNB4OZdxZ6y7xNAfEMmmt9GwBgcVhn9WFLX31wOj+G12Hd81/YMNxeKaOards/4WnoqDg2rYufeOLgeS/VFYKmiPaN9TSDeIn/50OmdRYNmEKr+jn1vBvzw6qYt4B3zSJK6oLtB2AfllJGopPLfZk1T6AMkU/0s3hzuDUXGpPHxGPCYU5dhcwemPcgVEY1yI3eajrb+pxFMU+kcsRBxhvsDX+g4tb2kiXCycEdQzgm8u1sdUNGt38LuAli2FcC30hAuhDiYrp1qBkaejDu6NbIpxuK9Rwk/FdEHqAFhKl+fbOWZC0TKviqjhVH06XtrUEGyU+9SjtbrxCkqCmqkqX2tL/LiIzr+nMuoC8l8riJfM76BZ05rYY9Qm9Ny1rbYneumvjtmeMHZNL+/6u523d7ZMdoeFe0wXh7YXkRo8v75djywmhhiHduay6SyVTZ94uWjmz9EY0xXDsrX8e8X69vH/6kjKoh9s+Is83pJIbvqU0J1hvu8YCsh2AkkFIqeGWv9+iPk2nw5q9TDF7Tz+p0ylWTEw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ovh-credentials
      namespace: cert-manager

