apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ovh-credentials
  namespace: cert-manager
spec:
  encryptedData:
    applicationSecret: AgCxH7ykYWdsf2sowByTBe9IX36DL+I1oV9sENku8GAfFGtCrmGyEVXayj/0jZHbDkGgRmhWsrHpnRxYKdbhAaHTE29/W4TLyqVXkr5jLZP/Lg+SUsOHesRDQntIJoaKjrLJ2FhXOcnbPAifo4nKuyLPp16yO1/6L7gQ52ee++WVsYB2EAQmPpSuSMuTQ/VtGQiqPhH2rxB27K81zEVWhEDOxiHUOPtIfqOhmKG9yX1ugKE8Hr/sQ6IVZDyh5UrYvzHdBl2icSWa9U7qZXXLi2aaWH0Fr4ynkcue0g0Re+xYHgOJ7OFXgyyhox2fV6scA0jyac0DsX+pFPq1rRKa8dWL3npYdhOKOjxTw59n2xUqW2w8IekLZoHFKX4TiCgRZNukwLkMPIiXlEWOabyYse4tDJDVv/ON3gNjsq0lM8CeCJeZU6Umy/ZwtJeWJMkbwjelmmovFMHarp7SkQzoBgRzvCqPl0X/HttCJH7d67uQa9EzA+fsAVJfFnu8uuT4cCXyHmzJeU373+zPwbldz7+ufOE+M8QuXfYpZMS3YDM9YOY1QqwwtS9JPgAizS7++As7Ifnv7U9iZjg2j8B4+LL4QO6JR4Pj3ObP5kb1+bAAKEDo7LCLFtCCQpf3V56PunbPgjTjZzD55LGSzIKyC5FeocHnDk4uty7L4oaS8bQThsA4dum0/uLwfJivJ4+KI3BeObHbETFvotfBP8QkgkVmKkyR0fTR8Kc3GBLDEu3gVg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ovh-credentials
      namespace: cert-manager
